import Head from 'next/head'
import Image from 'next/image'

export async function getStaticProps() {
  const QUERY = `
    query AllDrupalNodeArticle {
      allDrupalNodeArticle {
        nodes {
          id
          title
          created
        }
      }
    }
  `;

  const res = await fetch('https://adam-data-lay-ee3lsr-prod.api.netlify-connect.com/', {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      'Authorization': `Bearer ${process.env.NETLIFY_CONNECT_TOKEN}`
    },
    body: JSON.stringify({
      query: QUERY
    })
  })

  const json = await res.json();

  return {
    props: {
      data: json?.data?.allDrupalNodeArticle?.nodes || []
    }
  }
}

const Home: React.FC<{ data: any }>  = ({ data }) => {

  return (
    <>
      <Head>
        <title>Netlify Connect</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='container mx-auto px-20'>

        <div className="py-20 flex justify-center">
          <h1><img src="/logo.png" alt="Netlify" className='w-60'/></h1>
        </div>

        <div className=''>
          <div className='grid grid-cols-3 gap-8 py-6'>
            {data?.map((item: any) => (
              <div key={item?.id} className='bg-slate-200 p-4 rounded-lg'>
                <small>{new Date(item?.created).toDateString()}</small>
                <h3 className='text-xl mt-2'>{ item?.title }</h3>
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  )
}

export default Home;